"""
Django settings for ghostrr project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
#    'accounts.apps.AccountsConfig',
    'blog.apps.BlogConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   # add these
#    'rest_framework',
#    'oauth2_provider',
   'social_django',
#    'drf_social_oauth2',
    # 'corsheaders',
   # LOCAL
   'accounts',
   'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    	# add these
#    'corsheaders.middleware.CorsMiddleware',
   'django.middleware.common.CommonMiddleware',
   'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'ghostrr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['ghostrr/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'ghostrr.wsgi.application'

AUTHENTICATION_BACKENDS = (
    # 'social_core.backends.github.GithubOAuth2',
    # 'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    # 'drf_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
# REST_FRAMEWORK = {
#    'DEFAULT_AUTHENTICATION_CLASSES': (
#        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
#        'drf_social_oauth2.authentication.SocialAuthentication',
#    )
# }
# CORS_ALLOWED_ORIGINS = [
#    "http://localhost:8000",
#    "http://127.0.0.1:8000"
# ]

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if DEVELOPMENT_MODE is True:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
elif len(sys.argv) > 0 and sys.argv[1] != 'collectstatic':
    if os.getenv("DATABASE_URL", None) is None:
        raise Exception("DATABASE_URL environment variable not defined")
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL")),
    }

AUTH_USER_MODEL='accounts.User'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# SOCIAL_AUTH_PIPELINE = [  # Note: Sequence of functions matters here.
#     'social.pipeline.social_auth.social_details',  # 0
#     'social.pipeline.social_auth.social_uid',  # 1
#     'social.pipeline.social_auth.auth_allowed',  # 2
#     'social.pipeline.social_auth.social_user',  # 3
#     'social.pipeline.user.get_username',  # 4
#     'social.pipeline.social_auth.associate_by_email',  # 5
#     'social.pipeline.social_auth.associate_user',  # 6
#     'social.pipeline.social_auth.load_extra_data',  # 7
#     'social.pipeline.user.user_details',  # 8
# ]

# Adding conditional functions to pipepline.
# NOTE: Sequence of functions matters here.
# if config.GCPAuthentication.AUTO_CREATE_ACCOUNTS:
#     SOCIAL_AUTH_PIPELINE.insert(6, 'social.pipeline.user.create_user')


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# SOCIAL_AUTH_GITHUB_KEY = '16a4a6f93d87719992e6'
# SOCIAL_AUTH_GITHUB_SECRET = 'c9c93ba12639660c4c142a0d918022477393dc27'

SOCIAL_AUTH_FACEBOOK_KEY = '965291520898027'
SOCIAL_AUTH_FACEBOOK_SECRET = 'd2f892119bf1d3a4828e3a027831e281'

STATICFILES_DIRS= [
    os.path.join(BASE_DIR, 'static/')
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


LOGIN_URL = 'signin'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'index_page'


# LEvels credits
CREDITS = (10, 200)


# Email configurations
DEFAULT_FROM_EMAIL = 'support@ghostrr.com'
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER = 'netrobeweb@gmail.com'
EMAIL_HOST_PASSWORD = 'wpcgtxfwmiqnlbwv'


STRIPE_PUBLISHABLE_KEY = 'pk_test_51IElZYAPFPeEXZsZGZ64kmnkeXB51dvunK40rdp03RNhSQ3QUsDByAys8l4XwmUNI12zZSOSMV0Hckis3gLp04Hi00cDa1f0NB'
STRIPE_SECRET_KEY = 'sk_test_51IElZYAPFPeEXZsZQkI40drnRXmS8dsLmRqOv0EKqyqgMPXB65JgosR1aFREPL3lTHftssyzUxjVIS2xnBUp3mNC00OWm7tixI'
STRIPE_ENDPOINT_SECRET = 'whsec_xKDwUJBDBy6ygx0DzMfqicXlofaKJkj9'