# Generated by Django 3.1.5 on 2021-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Pro'), ('3', 'Enterprise')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
