# Generated by Django 3.1.5 on 2021-02-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='copy_length',
            field=models.CharField(choices=[('1', 'Minimum Word 500'), ('2', 'Maximum Word 1000')], max_length=1),
        ),
    ]
